apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-users
  labels:
    app: backend-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-users
  template:
    metadata:
      labels:
        app: backend-users
    spec:
      containers:
      - name: backend-users
        image: mrodelas/users
        ports:
        - containerPort: 8080
        env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: env-variables
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env-variables
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: env-variables
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: env-variables
                  key: POSTGRES_DB
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: env-variables
                  key: AWS_BUCKET
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: env-variables
                  key: AWS_REGION
            - name: AWS_PROFILE
              valueFrom:
                secretKeyRef:
                  name: env-variables
                  key: AWS_PROFILE
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-variables
                  key: JWT_SECRET
            - name: URL
              valueFrom:
                secretKeyRef:
                  name: env-variables
                  key: URL