apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-users
  name: backend-users
spec:
  #type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: backend-users
