apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverse-proxy
  name: reverse-proxy
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    app: reverse-proxy
