apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: "80"
      port: 80
      targetPort: 80
  selector:
    app: frontend
